### ISSUE TITLE
Restarting JuMPeR v0.6.0 development

### ISSUE THREAD

**Issue by SaidRahal** [TLKT0M/JuMPeR#7]
Plan objectives:
1. A roadmap to introduce the changes to JuMPeR v0.6.0 so that it is compatible with JuMP v0.19.0
2. Task assignment for team members: Said, Micheal and Tom
3. Duration two weeks from today (i.e., Friday 26/Nov).

**Comment by TLKT0M** [comment]
@SaidRahal @MichaelHartisch Said do you have some new Information for us?

**Comment by SaidRahal** [comment]
Hello @MichaelHartisch and @TLKT0M , I actually do. It took me a bit of time because I had to refresh my memories about the JuMPeR internals. 

1. I am attaching a word file which includes the changes impacting JuMPeR source code from JuMP 0.19 release notes. Some area quick  syntax changes. Others are more structural changes.
2. The current JuMPeR source includes some modifications that I need to remove. Most of them were not initially done by me and I did not have a lot of say. I can do that by end of Sunday. Otherwise, we can start by using the original JuMPeR source code. 
3. As for task assignment, I did not document the spots where the changes should be made. I am thinking of following your method which is execute JuMPeR using JuMP 0.19, and let the thrown errors guide us to the spots that should be changed. Basically, from a single error, we can use some logic to find other spots that require same changes easily.
4. To perform point 3 (i.e., working in series not parallel) smoothly, we should coordinate the time/days we work on the project. 

[JuMPv0_19ReleaseNoteAffectingJuMPeR.docx](https://github.com/TLKT0M/JuMPeR/files/7610858/JuMPv0_19ReleaseNoteAffectingJuMPeR.docx)

**Comment by SaidRahal** [comment]
You will both see that I created a branch named Said in main because when I first tried to branch out from the feature branch, I was not able to access the Newsvendor folder that contains the JuMPeR src. I did not know why did this was happen. Do you have an idea what may went wrong? 

The pull request I created is basically number 2 above. @TLKT0M,  point 5 in the attached document in my previous comment is a simple syntax-change assignment. It will be also an intro to get to know the @variable macro.

**Comment by TLKT0M** [comment]
Hello @SaidRahal ,
i try to answer your questions piece by piece.
1. Since I currently have a working week of over 60 hours, I find it difficult to define a day on which we can work together. In December, however, I should be able to release the project for my client, so that it will get better in January. Are you also open for days on the weekend?
2. I saw that you forked my repo, I don't think that was the point of working together. Maybe that was the problem why you didn't get into the feature branch.
3. What did I do:
3.1 I have distributed your changes via the repo. main => dev, feature.
Then I tested your code. Then I made a release with JuMPeR version 0.6.1 (0.0.1 over Ian, because of your changes).
3.2 I finished the "Terminator" sprint and created the new "Banana Joe" sprint by 12/12/21.
3.3 I have updated the Dockerfile and the julia_setup so that we are running on JuMP v0.19.2. and put this in the dev and feature branch.
3.4 I started to eliminate the error messages step by step, to remove the MathProgBase and the GLPKMathProgBaseInterface from the project and to replace them with MathOptInterface components. It struck me that I still lack knowledge to mathematically understand your NewsVendor problem. @MichaelHartisch 

When should we meet again?

**Comment by TLKT0M** [comment]
Adding to 2: If you want we can work together on This repo, but the Pull Request way is the right.

**Comment by SaidRahal** [comment]
Hello @TLKT0M:
1. I understand. My idea of defining a day was to avoid working on same chunk of code simultaneously so not to waste efforts. Do you know of a way we can communicate better this point? Yes I am available on Sundays. 
2. I forked your repo in the very beginning because I thought this is the way I can contribute. I know understand that it is through the Pull request. Still, I do not think this has to do with the issue in the feature branch. For example, today I branched from origin/UseMathOptInterface and the entire content of the repo appeared just fine (in contrary to the feature branch).
3. I was able to remove the old docker and build the new one fine. I am following the same approach in tracking errors. Which part of the newsvendor problem seemed difficult to comprehend? We can talk about that over the meeting.
I can meet next Tuesday 30/Nov at 10:00 pm my time.

**Comment by TLKT0M** [comment]
Hello @SaidRahal ,
Tuesday is my longest day at university. how does wednesday at 17:30 UTC sound to you? @MichaelHartisch , do we want to go through the NewsVedor problem immediately after Robust Optimization?

**Comment by MichaelHartisch** [comment]
17:30 = 5:30pm our time works for me. That should be 11.30am Said's time. Does that work for you Said?

@TLKT0M Yes, we can meet on at that time!

**Comment by SaidRahal** [comment]
Wednesday 17:30 UTC (i.e., 11:30am my time) sounds good for me. See you @MichaelHartisch , @TLKT0M  then.
